files:
  - source: /conf/labels.properties
    translation: /conf/%file_name%_%two_letters_code%.properties
  - source: /conf/descriptions.properties
    translation: /conf/%file_name%_%two_letters_code%.properties
  - source: /conf/ui.properties
    translation: /conf/%file_name%_%two_letters_code%.properties
  - source: /public/pages/*.md
    ignore:
      - /public/pages/*_*.md
    translation: /public/pages/%file_name%_%two_letters_code%.md
